cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view-cart'),
    path('update/<int:pk>', views.update_cart, name='update-cart'),
]

order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('checkout', views.checkout, name='checkout'),
    path('list', views.order_list, name='order-list'),
    path('view/<int:pk>', views.order_view, name='order-view'),
    path('canceled/<int:pk>', views.canceled, name='canceled'),
    path('finished/<int:pk>', views.finished, name='finished'),
]

tribalproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('complaint/', include('complaint.urls')),
    path('admindashboard/', include('admindashboard.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product
# Create your models here.


class Order(models.Model):
    orderid = models.CharField(max_length=20)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    shop_user = models.CharField(max_length=50)
    status = models.CharField(max_length=20, default="notstarted")
    subtotal = models.DecimalField(default=0, max_digits=50, decimal_places=2)
    shipping = models.DecimalField(default=0, max_digits=50, decimal_places=2)
    finaltotal = models.DecimalField(default=0, max_digits=50, decimal_places=2)
    date = models.DateTimeField(auto_now=True)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(default=0, max_digits=50, decimal_places=2)
    quantity = models.IntegerField()

order/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from cart.models import Cart, CartItem
from .models import Order, OrderItem
from datetime import datetime
import string
from account.models import Account
import random
from decimal import Decimal
# Create your views here.


@login_required
def checkout(request):
    account = Account.objects.get(user=request.user)
    if account.address == '' or account.area == '' or account.city == '' or account.state == '' or account.pincode == '':
        messages.error(request, 'Complete Your profile')
        return redirect('edit-profile')
    cart = Cart.objects.get(user=request.user)
    cartitem = CartItem.objects.filter(cart=cart)
    now = datetime.now()
    d = now.strftime("%Y-%m-%d %H:%M")
    order = Order(customer=request.user, shop_user=cartitem[0].product.user.username, orderid=id_generator(), date=d)
    order.save()
    order.subtotal = cart.total
    order.save()
    for i in range(len(cartitem)):
        order_item = OrderItem(order=order, product=cartitem[i].product, quantity=cartitem[i].quantity, price=cartitem[i].line_total)
        order_item.save()
    cart.delete()
    return redirect('order-view', order.id)


def id_generator(size=10, chars=string.ascii_uppercase + string.digits):
    the_id = "".join(random.choice(chars) for x in range(size))
    try:
        order = Order.objects.get(order_id=the_id)
        id_generator()
    except:
        return the_id

@login_required
def order_list(request):
    account = Account.objects.get(user=request.user)
    if account.category == 'customer':
        order = Order.objects.filter(customer=request.user)
    elif account.category == 'shopkeeper':
        order = Order.objects.filter(shop_user=request.user.username)
    elif request.user.is_superuser:
        order = Order.objects.all()
    else:
        messages.error(request, 'You cannot perform this operation')
        return redirect('home')
    if len(order) == 0:
        data = {'empty': True}
    else:
        data = {'empty': False}
    data['order'] = order
    return render(request, 'order/order_list.html', data)


@login_required
def order_view(request, pk):
    order = Order.objects.get(pk=pk)
    if request.method == 'POST':
        shipping = request.POST['delivery']
        order.shipping = Decimal(shipping)
        order.finaltotal = order.shipping+order.subtotal
        order.status = 'started'
        order.save()
    account = Account.objects.get(user=request.user)
    customer = Account.objects.get(user=order.customer)
    shopkeeper = Account.objects.get(username=order.shop_user)
    context = {'order': order, 'account': account, 'customer': customer, 'shopkeeper': shopkeeper}
    return render(request, 'order/order_view.html', context)


@login_required
def canceled(request,pk):
    order = Order.objects.get(pk=pk)
    order.status = 'canceled'
    order.save()
    return redirect('order-view', pk)


@login_required
def finished(request, pk):
    order = Order.objects.get(pk=pk)
    order.status = 'finished'
    order.save()
    return redirect('order-view', pk)

order/templates/order/order_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="col-sm-8 col-sm-offset-2">
            {% if empty %}

                <h1 align="center">No Order</h1>

            {% else %}

            <table style="margin-left: 50px" width="100%">

                {% for i in order %}
                <tr>
                    <td><a href="{% url 'order-view' i.id %}">{{ i.date }}({{ i.orderid }})</a> </td>
                </tr>
                <tr>
                    <td>Products Price : &#8377;{{ i.subtotal }}</td>
                    <td align="right">Status : </td>
                        {% ifequal i.status 'started' %}
                            <td style="color: orange">{{ i.status }}</td>
                        {% else %}
                        {% ifequal i.status 'finished' %}
                            <td style="color: green">{{ i.status }}</td>
                        {% else %}
                        {% ifequal i.status 'canceled' %}
                            <td style="color: red">{{ i.status }}</td>
                        {% else %}
                        {% ifequal i.status 'notstarted' %}
                            <td style="color: red">{{ i.status }}</td>
                        {% endifequal %}
                        {% endifequal %}
                        {% endifequal %}
                        {% endifequal %}

                </tr>
                <tr>
                    <td colspan="3"><HR/></td>
                </tr>

                {% endfor %}

            </table>
            {% endif %}
    </div>

{% endblock content %}

order/templates/order/order_view.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            Order id
        </div>
        <div class="col text-success">
            {{ order.orderid }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Customer
        </div>
        <div class="col text-success">
            {{ order.customer.username }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Shopkeeper
        </div>
        <div class="col text-success">
            {{ order.shop_user }}
        </div>
    </div>
    {% ifequal account.category 'customer' %}
    <div class="row">
        <div class="col">
            Shopkeeper Mobile no.
        </div>
        <div class="col text-success">
            {{ shopkeeper.mobile }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Shopkeeper Email id
        </div>
        <div class="col text-success">
            {{ shopkeeper.email }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Address
        </div>
        <div class="col text-success">
            {{ shopkeeper.address }}, {{ shopkeeper.area }}, {{ shopkeeper.city }}-{{ shopkeeper.pincode }}, {{ shopkeeper.state }}
        </div>
    </div>
    {% endifequal %}
    {% ifequal account.category 'shopkeeper' %}
    <div class="row">
        <div class="col">
            Customer Mobile no.
        </div>
        <div class="col text-success">
            {{ customer.mobile }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Customer Email id
        </div>
        <div class="col text-success">
            {{ customer.email }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Address
        </div>
        <div class="col text-success">
            {{ customer.address }}, {{ customer.area }}, {{ customer.city }}-{{ customer.pincode }}, {{ customer.state }}
        </div>
    </div>
    {% endifequal %}
        <div class="row">
            <div class="col-5 border font-weight-bold">
                Product Name
            </div>
            <div class="col border font-weight-bold">
                Product Price
            </div>
            <div class="col border font-weight-bold">
                Product Discount
            </div>
            <div class="col border font-weight-bold">
                Quantity
            </div>
            <div class="col border font-weight-bold">
                Final Price
            </div>
        </div>
        {% for i in order.orderitem_set.all %}
        <div class="row">
            <div class="col-5 border">
                {{ i.product.product_name }}
            </div>
            <div class="col border">
                &#8377;{{ i.product.product_price }}
            </div>
            <div class="col border">
                {{ i.product.product_discount }}%
            </div>
            <div class="col border">
                {{ i.quantity }}
            </div>
            <div class="col border">
                &#8377;{{ i.price }}
            </div>
        </div>
        {% endfor %}
    <div class="row">
        <div class="col">
            Status
        </div>
        {% ifequal order.status 'notstarted' %}
        <div class="col text-danger">
            Not Started
        </div>
        {% else %}
        {% ifequal order.status 'started' %}
        <div class="col text-warning">
            Started
        </div>
        {% else %}
        {% ifequal order.status 'canceled' %}
        <div class="col text-danger">
            Canceled
        </div>
        {% else %}
        {% ifequal order.status 'finished' %}
        <div class="col text-success">
            Finished
        </div>
        {% else %}
        {% endifequal %}
        {% endifequal %}
        {% endifequal %}
        {% endifequal %}
    </div>
    <div class="row">
        <div class="col">
            Subtotal
        </div>
        <div class="col text-success">
            &#8377;{{ order.subtotal }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Shipping
        </div>
        <div class="col text-success">
            &#8377;{{ order.shipping }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Final Total
        </div>
        <div class="col text-success">
            &#8377;{{ order.finaltotal }}
        </div>
    </div>
    {% ifequal account.category 'shopkeeper' %}
    {% ifequal order.status 'notstarted' %}
    <div class="row mt-3">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="delivery" class="sr-only">Password</label>
                <input name="delivery" type="text" class="form-control" id="delivery" placeholder="Delivery Charge">
              </div>
              <button type="submit" class="btn btn-primary mb-2">Accept</button>
            <a href="{% url 'canceled' order.id %}" class="btn btn-primary mb-2">Reject</a>
        </form>
    </div>
    {% endifequal %}
    {% ifequal order.status 'started' %}
    <div class="row">
        <div class="col">
            <a href="{% url 'finished' order.id %}" class="btn btn-primary float-right">Finished</a>
        </div>
    </div>
    {% endifequal %}
    {% endifequal %}
    {% ifequal account.category 'customer' %}
    {% ifnotequal order.status 'finished' %}
    {% ifnotequal order.status 'canceled' %}
    <div class="row">
        <div class="col">
            <a href="{% url 'canceled' order.id %}" class="btn btn-primary float-right">Canceled</a>
        </div>
    </div>
    {% endifnotequal %}
    {% endifnotequal %}
    {% endifequal %}
</div>

{% endblock content %}