cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view-cart'),
    path('update/<int:pk>', views.update_cart, name='update-cart'),
]

tribalproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('complaint/', include('complaint.urls')),
    path('admindashboard/', include('admindashboard.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product
# Create your models here.


class CartItem(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    line_total = models.DecimalField(default=0, max_digits=50, decimal_places=2)

    def __str__(self):
        return str(self.product.product_name)


class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=50, decimal_places=2, default=0.00)
    item_count = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)

templates/_alerts.html
{% if messages %}
{% for message in messages %}
<div id="message" class="container">
    <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
             Error
            {% else %}
                {{ message.tags|title }}
            {% endif %}
        </strong>
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <title>Welcome to Tribalmart</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <a class="navbar-brand" href="{% url 'home' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About us</a>
      </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'view-profile' %}">Profile</a>
        </li>
      <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">logout</a>
        </li>
      {% if user.is_superuser %}
      <li class="nav-item">
            <a class="nav-link" href="{% url 'user-list' %}">Users</a>
        </li>
      {% endif %}
        {% ifnotequal user.account.category 'cnf' %}
      <li class="nav-item">
            <a class="nav-link" href="{% url 'order-list' %}">order</a>
        </li>
        {% endifnotequal %}
      {% ifnotequal user.account.category 'shopkeeper' %}
      <li class="nav-item">
            <a class="nav-link" href="{% url 'complaint-list' %}">complaint</a>
        </li>
      {% endifnotequal %}
      {% ifequal user.account.category 'customer' %}
      <li class="nav-item">
           <a class="nav-link" href="{% url 'view-cart' %}"><img src="{% static 'shopping-cart.png' %}" width="20px" height="25px">Cart <span class="badge badge-dark">{{ user.cartitem_set.count }}</span> </a>
        </li>
        {% endifequal %}
      {% else %}
       <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
        {% endif %}
    </ul>
    <form method="GET" action="{% url 'search-product' %}" class="form-inline my-auto my-lg-0">
      <input class="form-control mr-sm-2" id="myInput" type="search" autocomplete="off" placeholder="Search" name="q" aria-label="Search" value="{{ request.GET.q }}" required>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

        {% block content %}
    {% endblock content %}
  <footer style="height: 100px;" class="my-auto pt-auto text-muted text-center text-small bg-dark">
  <HR>
    <p class="mb-1 text-white">&copy; 2020-2050 TribalMart</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms and Condition</a></li>
    </ul>
  </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>